/**
 * Module for all constants.
 */

const ERRORMESSAGE_COMMON = 'Please contact administrator. Account was not created';

const ERRORMESSAGE_POSTKILLBILLACCOUNT = 'KillBill account was not created';
const ERRORMESSAGE_CREATEACCCREDENTIALS = 'KillBill account credentials were not created';
const ERRORMESSAGE_SENDMAIL = 'Email message with verification link was not sent';
const ERRORMESSAGE_PUTACCOUNTINFO = 'An error occurred while changing account data';
const ERRORMESSAGE_GETACCOUNTINFO = 'An error occurred while retrieving account data';
const ERRORMESSAGE_POSTCHANGEPASSWORD = 'Old password is same as previous. Please set new password';
const ERRORMESSAGE_POSTCHANGEPASSWORD_DEFAULT = 'Failed to update password. Please try again';
const ERRORMESSAGE_GETACCOUNTIDBYCUSTOMFIELDPAIR = 'Username not found. Please try again';
const ERRORMESSAGE_GETCUSTOMFIELDBYACCOUNTID = 'Custom field for current request not found';
const ERRORMESSAGE_POSTCUSTOMFIELD = 'Custom field was not created';
const ERRORMESSAGE_GETACCOUNTEMAIL = 'Account was not found. Please try again or contact administrator';
const ERRORMESSAGE_POSTNEWACCOUNT = 'Email message with verification link was not sent';
const ERRORMESSAGE_POSTRECOVERYPASSWORD = 'Password recovery instructions were not send to email address. Please contact administrator or try again';
const ERRORMESSAGE_DELETECUSTOMFIELD = 'Custom field was not deleted';
const ERRORMESSAGE_GETEMAILVERIFICATIONLINK = 'Email address not verified. Please contact the administrator';
const ERRORMESSAGE_PAYMENT = 'Payment failed. Please try again or contact administrator';


const SUCCESSMESSAGE_POSTNEWACCOUNT = 'Account was successfully created. You will be redirected to login page in 5 sec. Please verify email address and try to login';
const SUCCESSMESSAGE_POSTACCOUNTINFO = 'Account was successfully updated';
const SUCCESSMESSAGE_POSTPASSWORDCHANGE = 'Password was updated successfully';
//const SUCCESSMESSAGE_GETPASSWORDRESETLINK = 'Please enter new password';
const SUCCESSMESSAGE_POSTPASSWORDRESETLINK = 'Password was successfully updated. You will be redirected to login page in 5 sec. Please try to login with new password';
const SUCCESSMESSAGE_POSTRECOVERYPASSWORD = 'Message with recovery link was sent to your email address';
const SUCCESSMESSAGE_GETEMAILVERIFICATIONLINK = 'Email address verified. Please try to login';

const MESSAGE_VERIFYEMAIL = 'Please verify your e-mail address by clicking on the following link: ';
const MESSAGE_PASSWORDEMAIL = 'Reset password by clicking the link: ';

module.exports = {
  ERRORMESSAGE_POSTKILLBILLACCOUNT: ERRORMESSAGE_POSTKILLBILLACCOUNT,
  ERRORMESSAGE_CREATEACCCREDENTIALS: ERRORMESSAGE_CREATEACCCREDENTIALS,
  ERRORMESSAGE_SENDMAIL: ERRORMESSAGE_SENDMAIL,
  ERRORMESSAGE_COMMON: ERRORMESSAGE_COMMON,
  SUCCESSMESSAGE_POSTNEWACCOUNT: SUCCESSMESSAGE_POSTNEWACCOUNT,
  MESSAGE_VERIFYEMAIL: MESSAGE_VERIFYEMAIL,
  MESSAGE_PASSWORDEMAIL: MESSAGE_PASSWORDEMAIL,
  ERRORMESSAGE_GETACCOUNTINFO: ERRORMESSAGE_GETACCOUNTINFO,
  ERRORMESSAGE_PUTACCOUNTINFO: ERRORMESSAGE_PUTACCOUNTINFO,
  SUCCESSMESSAGE_POSTACCOUNTINFO: SUCCESSMESSAGE_POSTACCOUNTINFO,
  ERRORMESSAGE_POSTCHANGEPASSWORD: ERRORMESSAGE_POSTCHANGEPASSWORD,
  ERRORMESSAGE_POSTCHANGEPASSWORD_DEFAULT: ERRORMESSAGE_POSTCHANGEPASSWORD_DEFAULT,
  SUCCESSMESSAGE_POSTPASSWORDCHANGE: SUCCESSMESSAGE_POSTPASSWORDCHANGE,
  ERRORMESSAGE_GETACCOUNTIDBYCUSTOMFIELDPAIR: ERRORMESSAGE_GETACCOUNTIDBYCUSTOMFIELDPAIR,
  //SUCCESSMESSAGE_GETPASSWORDRESETLINK: SUCCESSMESSAGE_GETPASSWORDRESETLINK,
  ERRORMESSAGE_GETCUSTOMFIELDBYACCOUNTID: ERRORMESSAGE_GETCUSTOMFIELDBYACCOUNTID,
  SUCCESSMESSAGE_POSTPASSWORDRESETLINK: SUCCESSMESSAGE_POSTPASSWORDRESETLINK,
  ERRORMESSAGE_POSTCUSTOMFIELD: ERRORMESSAGE_POSTCUSTOMFIELD,
  ERRORMESSAGE_GETACCOUNTEMAIL: ERRORMESSAGE_GETACCOUNTEMAIL,
  ERRORMESSAGE_POSTNEWACCOUNT: ERRORMESSAGE_POSTNEWACCOUNT,
  ERRORMESSAGE_POSTRECOVERYPASSWORD: ERRORMESSAGE_POSTRECOVERYPASSWORD,
  SUCCESSMESSAGE_POSTRECOVERYPASSWORD: SUCCESSMESSAGE_POSTRECOVERYPASSWORD,
  ERRORMESSAGE_DELETECUSTOMFIELD: ERRORMESSAGE_DELETECUSTOMFIELD,
  SUCCESSMESSAGE_GETEMAILVERIFICATIONLINK: SUCCESSMESSAGE_GETEMAILVERIFICATIONLINK,
  ERRORMESSAGE_GETEMAILVERIFICATIONLINK: ERRORMESSAGE_GETEMAILVERIFICATIONLINK,
  ERRORMESSAGE_PAYMENT: ERRORMESSAGE_PAYMENT

};

